
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_Uart_test(
		     //////////// CLOCK //////////
		     input 	  CLOCK_50,
		     input 	  CLOCK2_50,
		     input 	  CLOCK3_50,
		     input 	  CLOCK4_50,

		     //////////// SEG7 //////////
		     output [6:0] HEX0,
		     output [6:0] HEX1,
		     output [6:0] HEX2,
		     output [6:0] HEX3,
		     output [6:0] HEX4,
		     output [6:0] HEX5,

		     //////////// KEY //////////
		     input [3:0]  KEY,

		     //////////// LED //////////
		     output [9:0] LEDR,

		     //////////// SW //////////
		     input [9:0]  SW,

		     //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
		     inout [35:0] GPIO
		     );

   wire 			  enq_ready, enq_valid, deq_ready, deq_valid;
   wire[7:0] 			  enq_data, deq_data;
 
   assign deq_ready = enq_ready;
   assign enq_valid = deq_valid;
   assign enq_data  = deq_data;

   BufferedUart uart(.clk(CLOCK_50),
		     .reset(~KEY[0]),
		     .io_txd(GPIO[0]),
		     .io_rxd(GPIO[1]),
		     .io_enq_ready(enq_ready),
		     .io_enq_valid(enq_valid),
		     .io_enq_bits(enq_data),
		     .io_deq_ready(deq_ready),
		     .io_deq_valid(deq_valid),
		     .io_deq_bits(deq_data));

endmodule
